version: '3.7'
services:
  neo4j:
    image: neo4j:4.4.30-enterprise
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4JLABS_PLUGINS='["n10s"]'
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes